### ISSUE TITLE
image segmentation 

### ISSUE THREAD

**Issue by abhigoku10** [sbelharbi/deep-active-learning-for-joint-classification-and-segmentation-with-weak-annotator#1]
@sbelharbi  thanks for sharing the code base , i had few query 
can we use the source code for image segmentation or object detection based task module ? if so what are the changes to be made 

thanks in advance

**Comment by sbelharbi** [comment]
hi,

> can we use the source code for image segmentation or object detection based task module ?

yes.


> if so what are the changes to be made

it depends on what type of supervision you have.
in this work:
- each sample has global label (i.e. image class; can be extended to multi-label).
- the oracle provides pixel supervision only for selected samples.

what supervision do you have?

thanks

**Comment by abhigoku10** [comment]
@sbelharbi  thanks for the response 
I want to use this source code for  either 
1.object detection for autonomous driving scene for dataset like coco , bdd100k 
2.segmentation  for autonomous driving scene for dataset like cityscaper, bdd100k

**Comment by sbelharbi** [comment]
the short answer is that you can apply the method to any task. see cases below.

- **case 1: global labels are available**

the application of the code is straightforward. the only modification needed is how to estimate the pseudo-labels @ https://github.com/sbelharbi/deep-active-learning-for-joint-classification-and-segmentation-with-weak-annotator/blob/9192182b9a924735371c7525beb6319ed4119f2f/deeplearning/train.py#L640

in addition, you need to adapt the training to match the task (bounding boxes for example...).

**issue of multi-labels**: the method was evaluated on multi-class only but it can be extended to multi-labels.
in multi-class, for a sample with label = 10, only samples with label 10 are considered during knn.
in multi-label, one needs to define this membership.
we did some experiments on cityscapes dataset for a patent but we didnt update the paper.
we defined meta-labels which are predefined subsets of labels; and knn  operates only over meta-labels.
for example: meta-label 3 indicates a new label that holds the original labels {1, 2, 3}. meaning that, **typically/ideally**, a sample with meta-label 3 is expected to hold the labels {1, 2, 3} all at once. we defined a hashing function g, based on similarity between sets, that takes as input the set of labels in a sample, and maps it to a unique meta-label. you can define this as you like.

given a sample with meta-label X labeled by oracle, its neighbors based on meta-labels are more likely to have good pseudo-labels by model.


- **case 2: global labels are unavailable**

the only difference compared to case 1 is that you dont have any knowledge about global labels that were useful for knn measurement. meaning, instead of performing knn over samples from the same class only, you need to perform knn over the entire train dataset. you need good visual descriptors that capture colors/texture and probably shape if it is relevant.
modifications @ https://github.com/sbelharbi/deep-active-learning-for-joint-classification-and-segmentation-with-weak-annotator/blob/9192182b9a924735371c7525beb6319ed4119f2f/deeplearning/pairwise_similarity.py#L66

given a sample labeled by oracle, its neighbors based on appearance are more likely to have good pseudo-labels by model because they look similar.

thanks

**Comment by sbelharbi** [comment]
closing.
